stages:
  - build
  - test

test-job:
  stage: build
  script:
    - echo "Esta es la primera prueba."
    - echo "Revisaremos el contenido de las variables"
    - echo "CI_REGISTRY -> $CI_REGISTRY"
    - echo "CI_REGISTRY_USER -> $CI_REGISTRY_USER"
    - echo "CI_PROJECT_PATH -> $CI_PROJECT_PATH"
    - echo "TAG -> ${CI_COMMIT_SHORT_SHA}-${CI_JOB_ID}"
    - echo "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"


docker-master-build:
  # Instalar Docker dentro de Docker (Docker IN Docker = dind)
  services: 
    - docker:dind

  # La imagen de docker contiene todo lo que necesitamos para conectarse al docker daemon
  # es decir, permite correr todos los comandos de docker.
  image: docker:latest
  stage: build
  before_script:
    - export TAG=${CI_COMMIT_SHORT_SHA}-${CI_JOB_ID}
    # Hacemos login a docker
  script:
    # Creamos la imagen
    - docker build --pull --tag $CI_REGISTRY/${CI_PROJECT_PATH}:$TAG .
    - docker push $CI_REGISTRY/${CI_PROJECT_PATH}:$TAG
    
