[tool.black]
py36 = true
include = '\.pyi=$'
exclude = '''
/(
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | blib2to3
  | test/data
)/
'''
[tool.pytest.ini_options]
markers = [
    "slow: test takes more than 3s (deselect with '-m not slow')."
]
