version: '3.9'
services:
  twitter:
    image: registry.gitlab.com/cs-2022-2/proyecto/twitter:dev
    build:
      context: ../..
      dockerfile: containers/dev/Dockerfile
    ports:
      - '5050:80'
    volumes:
      - ../../:/app/
      - sessions:/app/sessions
      - ../../credentials.json:/credentials/credentials.json:ro
volumes:
  sessions:
